---
# version: '3.8'
services:
  # Servizio per il client (Next.js)
  client:
    build:
      context: .   
      dockerfile: Dockerfile  # Usa il Dockerfile per Next.js
    container_name: client-container   
    expose:
      - "3000"
    networks:
      - corso-network
    depends_on:
      - nginx
      - server
      - mysql
  # Servizio per Nginx
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - corso-network        
    restart: always    
    depends_on:
      - server
  # Servizio per il server (Node.js/Express)
  server:
    build:
      context: .   
      dockerfile: DockerFile.server  # Usa il Dockerfile del server
    container_name: server-container
    expose:
      - "5000"
    restart: always    
    networks:
      - corso-network
    depends_on:
      - mysql
  # Servizio per MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:      
      - MYSQL_ROOT_PASSWORD=22dj78dj
      - MYSQL_DATABASE=pippo 
    expose:
      - "3306"
    networks:
      - corso-network
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
networks:
  corso-network:
    driver: bridge
volumes:
  mysql_data: