# Usa Node.js come immagine base
FROM node:latest

# Crea una directory di lavoro
WORKDIR /CorsoCyber-AutoShop/server

# Copia i file package.json e package-lock.json
COPY package*.json ./

# Installa le dipendenze
#RUN npm install mysql2


# Installa le dipendenze
RUN npm install

# Copia il codice sorgente
COPY /server ./

# Espone la porta del server
EXPOSE 5000

# Comando per avviare l'app
CMD ["npm", "start"]